#!/usr/bin/env python3
import subprocess
import configparser


def get_vm_info(vm_name):
    get_ip_command = f"VBoxManage showvminfo --machinereadable \"{vm_name}\""
    vm_info = subprocess.check_output(get_ip_command, shell=True)
    ip_info = vm_info.decode("utf8") 

    config = configparser.RawConfigParser() 
    config.read_string("[vm_info]\n" + ip_info)
    return config['vm_info']

if __name__ == "__main__":
    runningvms_cmd="VBoxManage list vms --sorted"
    # Get running vm list from shell command
    output = subprocess.check_output(runningvms_cmd,shell=True)
    # Convert bytes to string
    output_decoded = output.decode("utf8")
    vms_list = output_decoded.split("\n")
    for vms in vms_list:
        if vms != "":
            vm_info = vms.split("\" {")
            vm_name = vm_info[0].replace("\"", "")
            vm_id = vm_info[1].replace("}", "")
            vm_info = get_vm_info(vm_name)
            if 'vrdeports' in vm_info:
                vm_vrde_ports = vm_info['vrdeports']
            else:
                vm_vrde_ports = "\"off\""
            vm_cfg_file = vm_info['CfgFile']
            print(vm_name, vm_vrde_ports, vm_cfg_file)