#!/usr/bin/env python3
import subprocess

def get_vm_ip(vm_name):
    get_vm_info_cmd= f"VBoxManage guestproperty enumerate '{vm_name}'|sort|grep IP"
    try:
        vm_network = subprocess.check_output(get_vm_info_cmd, shell=True)
        ip_info = vm_network.decode("utf8")
    except:
        ip_info = "None\n"
    return ip_info

def get_vm_network(vm_name):
    get_vm_info_cmd= f"VBoxManage showvminfo --machinereadable '{vm_name}'|grep -E  '(nic|network|adapter|vboxnet)'"
    vm_network = subprocess.check_output(get_vm_info_cmd, shell=True)
    vm_net_info  = vm_network.decode("utf8") 
    return vm_net_info 

if __name__ == "__main__":
    runningvms_cmd="VBoxManage list runningvms --sorted"
    # Get running vm list from shell command
    output = subprocess.check_output(runningvms_cmd,shell=True)
    # Convert bytes to string
    output_decoded = output.decode("utf8")
    vms_list = output_decoded.split("\n")
    for vms in vms_list:
        if vms != "":
            vm_info = vms.split("\" {")
            vm_name = vm_info[0].replace("\"", "")
            vm_id = vm_info[1].replace("}", "")
            print("# " + vm_name + " #\n")
            print(get_vm_ip(vm_name))
            print(get_vm_network(vm_name))
            print("")